-- Sentinel AI Infrastructure
-- Tables for knowledge, autonomous actions, and self-evolving strategies

-- 1. Knowledge Base: Stores patterns, diagnoses, and recommended actions
CREATE TABLE IF NOT EXISTS public.sentinel_knowledge (
    id                  uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at          timestamptz DEFAULT now(),
    pattern_hash        text UNIQUE, -- Hash of the error pattern for deduplication
    error_signature     text NOT NULL, -- Human/AI readable signature of the issue
    diagnosis           text,
    recommended_action  text,
    success_count       int DEFAULT 0,
    failure_count       int DEFAULT 0,
    last_applied_at     timestamptz,
    is_verified         boolean DEFAULT false
);

-- 2. Strategies: Dynamic heuristics generated by the AI
CREATE TABLE IF NOT EXISTS public.sentinel_strategies (
    id                  uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at          timestamptz DEFAULT now(),
    name                text NOT NULL,
    condition_prompt    text NOT NULL, -- LLM instruction for when to use this
    action_template     jsonb NOT NULL, -- Structured action to take
    confidence_score    float DEFAULT 0.5,
    version             int DEFAULT 1,
    is_active           boolean DEFAULT true
);

-- 3. Actions: Audit log of autonomous healing operations
CREATE TABLE IF NOT EXISTS public.sentinel_actions (
    id                  uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    ts                  timestamptz DEFAULT now(),
    log_id              uuid REFERENCES public.system_logs(id),
    strategy_id         uuid REFERENCES public.sentinel_strategies(id),
    action_type         text NOT NULL, -- switch_provider, retry_order, adjust_settings, notify_admin
    status              text DEFAULT 'pending', -- pending, executed, failed
    effectiveness       int DEFAULT 0, -- -1 (bad), 0 (neutral), 1 (fixed)
    reasoning           text, -- Why the AI chose this action
    result              jsonb,
    metadata            jsonb
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_sentinel_knowledge_hash ON public.sentinel_knowledge(pattern_hash);
CREATE INDEX IF NOT EXISTS idx_sentinel_actions_ts ON public.sentinel_actions(ts DESC);
CREATE INDEX IF NOT EXISTS idx_sentinel_actions_status ON public.sentinel_actions(status);

-- RLS: Admin only
ALTER TABLE public.sentinel_knowledge ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sentinel_strategies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sentinel_actions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admins_manage_sentinel_knowledge" ON public.sentinel_knowledge FOR ALL USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));
CREATE POLICY "admins_manage_sentinel_strategies" ON public.sentinel_strategies FOR ALL USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));
CREATE POLICY "admins_manage_sentinel_actions" ON public.sentinel_actions FOR ALL USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

-- Enable Realtime for the dashboard
ALTER PUBLICATION supabase_realtime ADD TABLE public.sentinel_actions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sentinel_strategies;
